# Generated by Django 4.2.6 on 2023-10-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_alter_useraccount_options_useraccount_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profile_pic',
            field=models.ImageField(default='faces/profile.png', upload_to='faces/'),
        ),
    ]
