# Generated by Django 4.2.6 on 2023-10-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='Easy-to-follow video & guides show you how to draw animals, people & more.', max_length=500),
        ),
        migrations.AddField(
            model_name='category',
            name='time',
            field=models.IntegerField(default=30),
        ),
    ]
