# Generated by Django 4.2.6 on 2023-10-25 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_notice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name_plural': 'QUIZ ANSWER'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'QUIZ TOPIC'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name_plural': 'QUICK NOTICE'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'QUIZ QUESTION'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='quiz.category', verbose_name='Topic'),
        ),
    ]
