# Generated by Django 4.2.6 on 2023-10-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'NEWSLETTER',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'CONTACT'},
        ),
    ]
