# Generated by Django 4.2.6 on 2023-10-17 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_expiredquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiredquiz',
            name='submited_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quizhistory',
            name='submited_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
