# Generated by Django 4.2.6 on 2023-10-20 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_expiredquiz_submited_time_quizhistory_submited_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiredquiz',
            name='submited_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
