# Generated by Django 4.2.6 on 2023-10-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_alter_expiredquiz_submited_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizhistory',
            name='dept',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quizhistory',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quizhistory',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
