# Generated by Django 4.2.6 on 2023-10-25 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_quizhistory_dept_quizhistory_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expiredquiz',
            options={'verbose_name_plural': 'COMPLETED QUIZ'},
        ),
        migrations.AlterModelOptions(
            name='quizhistory',
            options={'verbose_name_plural': 'QUIZ HISTORY'},
        ),
    ]
